output_dir:
  wine: ./output/wine_output

data:
  dir:
    wine:
      data_dir: ./dataset/wine/winequality-red.csv
      train_set_dir: ./dataset/wine/train_winequality-red.csv
      test_set_dir: ./dataset/wine/test_winequality-red.csv

  input_dim:
    wine:
      input_dim: 11

ckpt:
  ckpt_save_interval: 1

parameters:
  dropout_prob: 0.1
  num_epochs: 40
  batch_size: 100
  learning_rate: 0.1
  num_networks: 40

